export const SECTION_TYPES = [
    'blocks',
    'items',
    'mobs',
    'mob_variants',
    'effects',
    'enchantments',
    'advancements',
    'paintings',
    'biomes',
    'structures',
];

export const SECTION_META = {
    blocks: {
        label: 'Blocks',
        stateKey: 'showBlocks',
        gridClass: null,
        usePlaceholders: true,
        detailStats: true,
        statsTable: true,
    },
    items: {
        label: 'Items',
        stateKey: 'showItems',
        gridClass: null,
        usePlaceholders: true,
        detailStats: true,
        statsTable: true,
    },
    mobs: {
        label: 'Mobs',
        stateKey: 'showMobs',
        gridClass: 'mobs-grid',
        usePlaceholders: false,
        detailStats: true,
        statsTable: true,
    },
    mob_variants: {
        label: 'Mob Variants',
        stateKey: 'showMobVariants',
        gridClass: 'mobs-grid',
        usePlaceholders: false,
        detailStats: true,
        statsTable: false,
    },
    effects: {
        label: 'Effects',
        stateKey: 'showEffects',
        gridClass: 'effects-grid',
        usePlaceholders: false,
        detailStats: true,
        statsTable: true,
    },
    enchantments: {
        label: 'Enchantments',
        stateKey: 'showEnchantments',
        gridClass: 'enchantments-grid',
        usePlaceholders: false,
        detailStats: true,
        statsTable: true,
    },
    advancements: {
        label: 'Advancements',
        stateKey: 'showAdvancements',
        gridClass: 'advancements-grid',
        usePlaceholders: false,
        detailStats: true,
        statsTable: true,
    },
    paintings: {
        label: 'Paintings',
        stateKey: 'showPaintings',
        gridClass: 'paintings-grid',
        usePlaceholders: false,
        detailStats: true,
        statsTable: false,
    },
    biomes: {
        label: 'Biomes',
        stateKey: 'showBiomes',
        gridClass: 'biomes-grid',
        usePlaceholders: false,
        detailStats: true,
        statsTable: true,
    },
    structures: {
        label: 'Structures',
        stateKey: 'showStructures',
        gridClass: null,
        usePlaceholders: false,
        detailStats: false,
        statsTable: true,
    },
};

export const DETAIL_STATS_ORDER = [
    'blocks',
    'items',
    'mobs',
    'mob_variants',
    'effects',
    'enchantments',
    'advancements',
    'paintings',
    'biomes',
];

export const STATS_COLUMNS_ORDER = [
    'items',
    'blocks',
    'mobs',
    'effects',
    'enchantments',
    'advancements',
    'biomes',
    'structures',
];
