export const CARD_CLASSES = Object.freeze({
    HEADER_ROW: 'card-header-row',
    STATUS_BADGE: 'card-status-badge',
    DETAIL_HEADER: 'detail-header',
    DETAIL_LINK: 'detail-link',
    DETAIL_CLOSE_BUTTON: 'detail-close-btn',
    DETAIL_HEADER_SPACER: 'detail-header-spacer',
    SUBTITLE_ROW: 'card-subtitle-row',
    SUBTITLE_TEXT: 'card-subtitle-text',
    SUBTITLE_LINK: 'card-subtitle-link',
    SUBTITLE_SEPARATOR: 'card-subtitle-separator',
    SECTION: 'card-section',
    SECTION_TITLE: 'section-title',
    GRID: 'element-grid',
    GRID_ITEM: 'grid-item',
    CLICKABLE_CARD: 'clickable-card',
    TOOLTIP_WRAPPER: 'tooltip-wrapper',
    NOTABLE_CONTENT: 'notable-changes-content',
    NOTABLE_SUBSECTION: 'notable-subsection',
    NOTABLE_SUBSECTION_TITLE: 'notable-subsection-title',
    NOTABLE_LIST: 'notable-list',
    NOTABLE_ENTRY: 'notable-entry',
    NOTABLE_ENTRY_IMAGE: 'notable-entry-image',
    NOTABLE_ENTRY_BODY: 'notable-entry-body',
    NOTABLE_ENTRY_DESC: 'notable-entry-desc',
    NOTABLE_ENTRY_SUBLIST: 'notable-entry-sublist',
});

export const CARD_DATA = Object.freeze({
    SECTION: 'section',
    DETAIL_TYPE: 'detailType',
    DETAIL_ID: 'detailId',
    TOOLTIP: 'tooltip',
    IDENTIFIER: 'identifier',
    WIKI: 'wiki',
});
